# Generated by Django 5.1.5 on 2025-02-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_image_url', models.ImageField(default='', upload_to='shop/images')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_des', models.CharField(max_length=40)),
                ('product_ingredient', models.FloatField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_manuf_date', models.DateField()),
                ('product_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=20)),
                ('comp_mob_no', models.CharField(max_length=13)),
                ('comp_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_name', models.CharField(max_length=20)),
                ('purchase_desc', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_return',
            fields=[
                ('sel_ret_id', models.AutoField(primary_key=True, serialize=False)),
                ('sal_ret_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='unit_of_measurement',
            fields=[
                ('unit_measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_measurement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Area_id', models.AutoField(primary_key=True, serialize=False)),
                ('Area_name', models.CharField(max_length=20)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.city')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_expiry_date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product_company'),
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product_company')),
            ],
        ),
        migrations.CreateModel(
            name='Product_photo',
            fields=[
                ('pro_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_photo_url', models.ImageField(default='', upload_to='shop/images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_return',
            fields=[
                ('purchase_return_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_return_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('purchase_return_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_person',
            fields=[
                ('Del_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('Del_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.role')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('SGST', models.FloatField()),
                ('CGST', models.FloatField()),
                ('Sales_date', models.DateTimeField()),
                ('order_status', models.CharField(default='assigned', max_length=20)),
                ('Del_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.delivery_person')),
                ('pre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.sales'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('cheque', 'cheque'), ('other', 'other')], max_length=50)),
                ('date', models.DateTimeField()),
                ('Total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.sales')),
            ],
        ),
        migrations.CreateModel(
            name='sales_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.sales')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sel_ret_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.sales_return'),
        ),
        migrations.CreateModel(
            name='sales_return_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('sel_ret_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.sales_return')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.area')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.shop'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.state'),
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('Sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sub_cat_name', models.CharField(max_length=20)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.subcategory'),
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('suppliers_id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliers_name', models.CharField(max_length=20)),
                ('suppliers_contact', models.CharField(max_length=13)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product_company')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='suppliers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.suppliers'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_measurement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.unit_of_measurement'),
        ),
        migrations.CreateModel(
            name='unit_of_measurement_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('unit_measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.unit_of_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=2)),
                ('Address', models.CharField(max_length=20)),
                ('Mob_no', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.area')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.role')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.shop')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user'),
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('rate_Date', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacks', models.CharField(max_length=25)),
                ('Date', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user')),
            ],
        ),
        migrations.CreateModel(
            name='complains',
            fields=[
                ('cmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_message', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('cmp_response', models.CharField(max_length=20)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.user')),
            ],
        ),
    ]
