# Generated by Django 5.1.5 on 2025-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('pending', 'Pending')], default='assigned', max_length=20),
        ),
    ]
