# Generated by Django 5.1.5 on 2025-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_sales_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_desc',
            field=models.CharField(max_length=50),
        ),
    ]
