# Generated by Django 5.1.5 on 2025-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_purchase_purchase_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_return',
            name='reason',
            field=models.CharField(max_length=50),
        ),
    ]
