# Generated by Django 5.1.5 on 2025-02-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_purchase_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default='customer', on_delete=django.db.models.deletion.CASCADE, to='owner.role'),
        ),
    ]
