# Generated by Django 5.1.5 on 2025-02-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Sales_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sel_ret_id',
        ),
    ]
