# Generated by Django 5.1.5 on 2025-02-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
