# Generated by Django 5.1.5 on 2025-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_category_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_photo_url',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.DeleteModel(
            name='Product_photo',
        ),
    ]
