# Generated by Django 5.1.5 on 2025-02-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_product_pro_photo_url_delete_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_photo_url',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
