# Generated by Django 5.1.5 on 2025-02-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('owner', '0010_alter_product_pro_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=2)),
                ('Address', models.CharField(max_length=20)),
                ('Mob_no', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.area')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('role_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner.role')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.shop')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
