# Generated by Django 5.1.5 on 2025-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
