# Generated by Django 5.1.5 on 2025-02-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_batch_batch_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
