# Generated by Django 5.1.5 on 2025-02-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='CustomUser',
        ),
    ]
