# Generated by Django 5.1.5 on 2025-02-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='16-02-2025'),
            preserve_default=False,
        ),
    ]
