# Generated by Django 5.1.5 on 2025-02-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_remove_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
