# Generated by Django 5.1.5 on 2025-02-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
